services:
  app:
    build:
      args:
        user: me
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: letter-checker
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    networks:
      - letter-checker
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - letter-checker
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - letter-checker
networks:
  letter-checker:
    driver: bridge